# Generated by Django 6.1 on 2026-08-18 10:43

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_meal_voucher_limit', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
                'abstract': False,
            },
        ),
    ]
